### ISSUE TITLE
运行carthage update --no-use-binaries --platform mac,ios的时候提示编译错误

### ISSUE THREAD

**Issue by laitongxue000** [zlyBear/BearFree#16]
[LaiTongXue@Mr-Lais-MacBook-Pro:] ~/Downloads/RabbitVpnDemo $ carthage update --no-use-binaries --platform mac,ios
*** Fetching CommonCrypto
*** Fetching NEKit
*** Fetching CocoaAsyncSocket
*** Fetching Resolver
*** Fetching CocoaLumberjack
*** Fetching tun2socks
*** Checking out NEKit at "4687dbe0ef880d876e171836ab0fc761af8e76c6"
*** Checking out tun2socks at "0.7.0"
*** Checking out CocoaLumberjack at "3.7.0"
*** Checking out CommonCrypto at "v1.1.0"
*** Checking out YamlSwift at "3.4.3"
*** Checking out CocoaAsyncSocket at "7.6.5"
*** Checking out MMDB-Swift at "0.5.0"
*** Checking out Resolver at "0.2.0"
*** Checking out Sodium-framework at "v1.0.10.1"
*** xcodebuild output can be found in /var/folders/mq/93cdzpy54y3_wl6xp59vdg7r0000gn/T/carthage-xcodebuild.ycqUEn.log
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/LaiTongXue/Library/Caches/org.carthage.CarthageKit/DerivedData/12.3_12C33/CocoaAsyncSocket/7.6.5/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/LaiTongXue/Library/Caches/org.carthage.CarthageKit/DerivedData/12.3_12C33/CocoaAsyncSocket/7.6.5/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Users/LaiTongXue/Downloads/RabbitVpnDemo/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mq/93cdzpy54y3_wl6xp59vdg7r0000gn/T/carthage-xcodebuild.ycqUEn.log

我的xcode是12.3的，编译的时候就一直报错

**Comment by ronin66666** [comment]
兄弟解决了吗，我的是编译到Sodium-iOS这个库的时候报错，其他还没问题
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjack" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace
*** Building scheme "CommonCrypto-iOS" in CommonCrypto.xcodeproj
*** Building scheme "Eureka" in Eureka.xcworkspace
*** Building scheme "MMDB-iOS" in MMDB.xcodeproj
*** Building scheme "Resolver-iOS" in Resolver.xcodeproj
*** Building scheme "Sodium-iOS" in Sodium.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/liangcheng/Desktop/vpnDemo/vpndemo/Carthage/Checkouts/Sodium-framework/Sodium.xcodeproj -scheme Sodium-iOS -configuration Release -derivedDataPath /Users/liangcheng/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/Sodium-framework/v1.0.10.1 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=C96E6505-D2E8-4DF0-B55C-1130993EEE28 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO (launched in /Users/liangcheng/Desktop/vpnDemo/vpndemo/Carthage/Checkouts/Sodium-framework)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/ll/dw02wmqx1qg4s9mj5nl7xx4c0000gn/T/carthage-xcodebuild.5Hyp6b.log

**Comment by ronin66666** [comment]
我按照这个方法解决了这个问题
https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506

**Comment by Woxiee** [comment]
xcode新版本无法搞定,求解决方案

**Comment by Woxiee** [comment]
> xcode新版本无法搞定,求解决方案

把Xcode版本降低到11.3 就能正常carthage update 成功

**Comment by maybeliu** [comment]
> 我按照这个方法解决了这个问题 [Carthage/Carthage#3019 (comment)](https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506)

tmp.xcconfig  用创建这个的方法可以解决

**Comment by maybeliu** [comment]
> 我按照这个方法解决了这个问题 [Carthage/Carthage#3019 (comment)](https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506)

tmp.xcconfig  用创建这个的方法可以解决
