### ISSUE TITLE
修改Bundle identifier之后，运行项目，就没办法上网了，请问如何解决呢？

### ISSUE THREAD

**Issue by WangEnMaoFly** [zlyBear/BearFree#3]
修改Bundle identifier之后，运行项目，就没办法上网了，请问如何解决呢？求大神支个招。

**Comment by zlyBear** [comment]
需要用你自己的开发者账号重新配置的

**Comment by zlyBear** [comment]
> 修改Bundle identifier之后，运行项目，就没办法上网了，请问如何解决呢？求大神支个招。
需要用你自己的开发者账号重新配置的

**Comment by zlyBear** [comment]
> 修改Bundle identifier之后，运行项目，就没办法上网了，请问如何解决呢？求大神支个招。

需要用你自己的开发者账号重新进行配置

**Comment by wuyilong80** [comment]
您好 我也遇到相同的問題 開發者帳號已經重新配置過了 手機上也有出現vpn連線的圖示 但就是沒有網路 請問我是什麼地方沒做好嗎？

**Comment by SaviorWu** [comment]
喊爸爸
在override func viewDidLoad()加上如下代码：
let url = URL(string:"https://www.baidu.com");
        URLSession(configuration: .default).dataTask(with: url!, completionHandler: {
            (data, rsp, error) in
            //do some thing
            print("visit network ok");
        }).resume()
