### ISSUE TITLE
有后门软件

### ISSUE THREAD

**Issue by hhhaiai** [zlyBear/BearFree#6]
> 在创建应用之前我们需要安装NEProviderTargetTemplates.pkg，在xcode10.12之后苹果在xcode中删除了这个文件，为什么？可能和中国区被下架的那些VXN一样的原因吧。好在我们还可以从老版本的xcode中提取这个文件，链接在此点击下载 ，提取码：18ek，要低调，安装好后重启xcode。

z这里下载的模板不生效，并且，有后门软件，自从安装后，机器无法联网。即将重装

千万注意！！

**Comment by zlyBear** [comment]
厉害厉害，后门都出来了

**Comment by hhhaiai** [comment]
自从用了这个后，直接出了问题，mac的DNS一直被干扰

**Comment by hhhaiai** [comment]
并且 xcode的network extension也没出来
