### ISSUE TITLE
startVPNTunnel没有创建成功

### ISSUE THREAD

**Issue by bryant24** [zlyBear/BearFree#9]
执行到try manager.connection.startVPNTunnel(options:[:])，没有回调到startTunnel(),也没有抛出异常，vpn没有创建，是什么原因？也没有日志

**Comment by bryant24** [comment]
调试了下PacketTunnel的进程，发现有一个yaml文件的解析错误，NEKitRule.conf这个文件在Yaml.load时出现问题了

**Comment by bryant24** [comment]
调试了下发现是Yamlswift 这个库 对解析NETKitRule.conf这个文件有问题，缩进不正确，把conf文件内容的 - 前加空格再对齐就好了，不过，到现在为止 我还不能fq，浏览器里不能访问www.google.com，不知道什么原因

**Comment by 50611** [comment]
什么原因。。我也遇到了
